name: nx-monorepo
volumes:
  postgres_data:
  cache_data:
services:
  postgres:
    hostname: nx-monorepo-starter-postgres
    container_name: nx-monorepo-starter-postgres
    image: postgres:18.0-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    depends_on:
      redis:
        condition: service_started
    restart: unless-stopped
  redis:
    hostname: nx-monorepo-starter-redis
    container_name: nx-monorepo-starter-redis
    image: redis:8.2.3-alpine
    ports:
      - 6379:6379
    volumes:
      - cache_data:/data
    command: redis-server --save 60 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    restart: unless-stopped
